#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${HOUSTON_DB_USER} WITH SUPERUSER PASSWORD '${HOUSTON_DB_PASSWORD}';
    CREATE DATABASE ${HOUSTON_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${HOUSTON_DB_NAME} TO ${HOUSTON_DB_USER};
EOSQL
