"""empty message

Revision ID: 04a5695ac4a2
Revises: 99b2ab9e9970
Create Date: 2021-03-19 13:15:55.528079

"""

# revision identifiers, used by Alembic.
revision = '04a5695ac4a2'
down_revision = '99b2ab9e9970'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter_guid', app.extensions.GUID(), nullable=True))
        batch_op.alter_column('owner_guid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_encounter_submitter_guid'), ['submitter_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_encounter_submitter_guid_user'), 'user', ['submitter_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_encounter_submitter_guid_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_encounter_submitter_guid'))
        batch_op.alter_column('owner_guid',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.drop_column('submitter_guid')

    # ### end Alembic commands ###
