# -*- coding: utf-8 -*-
"""empty message

Revision ID: 056aec308d6e
Revises: 09517e00a2f8
Create Date: 2022-01-27 01:29:25.209116

"""
from alembic import op

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '056aec308d6e'
down_revision = '09517e00a2f8'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.alter_column(
            'mission_guid', existing_type=app.extensions.GUID(), nullable=False
        )
        batch_op.create_unique_constraint(
            batch_op.f('uq_mission_task_mission_guid'), ['mission_guid', 'title']
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('uq_mission_task_mission_guid'), type_='unique'
        )
        batch_op.alter_column(
            'mission_guid', existing_type=app.extensions.GUID(), nullable=True
        )

    # ### end Alembic commands ###
