# -*- coding: utf-8 -*-
"""empty message

Revision ID: 09517e00a2f8
Revises: 3fc0b28658aa
Create Date: 2022-01-25 21:31:10.397607

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '09517e00a2f8'
down_revision = '3fc0b28658aa'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_asset_participation', schema=None) as batch_op:
        batch_op.drop_index('ix_mission_asset_participation_created')
        batch_op.drop_index('ix_mission_asset_participation_updated')

    op.drop_table('mission_asset_participation')
    with op.batch_alter_table('mission_collection', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('mission_guid', app.extensions.GUID(), nullable=False)
        )
        batch_op.create_index(
            batch_op.f('ix_mission_collection_mission_guid'),
            ['mission_guid'],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_mission_collection_mission_guid_mission'),
            'mission',
            ['mission_guid'],
            ['guid'],
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_collection', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_mission_collection_mission_guid_mission'), type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_mission_collection_mission_guid'))
        batch_op.drop_column('mission_guid')

    op.create_table(
        'mission_asset_participation',
        sa.Column('created', sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column('viewed', sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column(
            'mission_guid', app.extensions.GUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'asset_guid', app.extensions.GUID(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['asset_guid'],
            ['asset.guid'],
            name='fk_mission_asset_participation_asset_guid_asset',
        ),
        sa.ForeignKeyConstraint(
            ['mission_guid'],
            ['mission.guid'],
            name='fk_mission_asset_participation_mission_guid_mission',
        ),
        sa.PrimaryKeyConstraint(
            'mission_guid', 'asset_guid', name='pk_mission_asset_participation'
        ),
    )
    with op.batch_alter_table('mission_asset_participation', schema=None) as batch_op:
        batch_op.create_index(
            'ix_mission_asset_participation_updated', ['updated'], unique=False
        )
        batch_op.create_index(
            'ix_mission_asset_participation_created', ['created'], unique=False
        )

    # ### end Alembic commands ###
