# -*- coding: utf-8 -*-
"""empty message

Revision ID: 0d4a39233a8a
Revises: 2d9fb3118162
Create Date: 2022-07-20 20:04:23.224213

"""
import sqlalchemy as sa
from alembic import op

import app
import app.extensions

# revision identifiers, used by Alembic.
revision = '0d4a39233a8a'
down_revision = '2d9fb3118162'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sighting_taxonomies',
        sa.Column('sighting_guid', app.extensions.GUID(), nullable=False),
        sa.Column('taxonomy_guid', app.extensions.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['sighting_guid'],
            ['sighting.guid'],
            name=op.f('fk_sighting_taxonomies_sighting_guid_sighting'),
        ),
        sa.PrimaryKeyConstraint(
            'sighting_guid', 'taxonomy_guid', name=op.f('pk_sighting_taxonomies')
        ),
    )
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decimal_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('decimal_longitude', sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column('location_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.add_column(sa.Column('verbatim_locality', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=40), nullable=True))
        batch_op.add_column(
            sa.Column('custom_fields', app.extensions.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('taxonomy_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f('ix_encounter_location_guid'), ['location_guid'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_encounter_taxonomy_guid'), ['taxonomy_guid'], unique=False
        )
        batch_op.drop_column('version')

    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('time_of_birth', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_of_death', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('taxonomy_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('custom_fields', app.extensions.JSON(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f('ix_individual_taxonomy_guid'), ['taxonomy_guid'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_individual_time_of_birth'), ['time_of_birth'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_individual_time_of_death'), ['time_of_death'], unique=False
        )
        batch_op.drop_column('version')

    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decimal_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('decimal_longitude', sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column('location_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verbatim_locality', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('custom_fields', app.extensions.JSON(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f('ix_sighting_location_guid'), ['location_guid'], unique=False
        )
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_index(batch_op.f('ix_sighting_location_guid'))
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('verbatim_locality')
        batch_op.drop_column('comments')
        batch_op.drop_column('location_guid')
        batch_op.drop_column('decimal_longitude')
        batch_op.drop_column('decimal_latitude')

    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_index(batch_op.f('ix_individual_time_of_death'))
        batch_op.drop_index(batch_op.f('ix_individual_time_of_birth'))
        batch_op.drop_index(batch_op.f('ix_individual_taxonomy_guid'))
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('taxonomy_guid')
        batch_op.drop_column('time_of_death')
        batch_op.drop_column('time_of_birth')
        batch_op.drop_column('sex')
        batch_op.drop_column('comments')

    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_index(batch_op.f('ix_encounter_taxonomy_guid'))
        batch_op.drop_index(batch_op.f('ix_encounter_location_guid'))
        batch_op.drop_column('taxonomy_guid')
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('sex')
        batch_op.drop_column('verbatim_locality')
        batch_op.drop_column('location_guid')
        batch_op.drop_column('decimal_longitude')
        batch_op.drop_column('decimal_latitude')

    op.drop_table('sighting_taxonomies')
    # ### end Alembic commands ###
