"""empty message

Revision ID: 11cd9b6d0564
Revises: fc3498d68351
Create Date: 2020-12-18 11:38:11.308456

"""

# revision identifiers, used by Alembic.
revision = '11cd9b6d0564'
down_revision = 'fc3498d68351'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sighting_guid', app.extensions.GUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_encounter_sighting_guid'), ['sighting_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_encounter_sighting_guid_sighting'), 'sighting', ['sighting_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_encounter_sighting_guid_sighting'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_encounter_sighting_guid'))
        batch_op.drop_column('sighting_guid')

    # ### end Alembic commands ###
