# -*- coding: utf-8 -*-
"""empty message

Revision ID: 1cdb69cbdcaa
Revises: afedda6596b9
Create Date: 2022-05-30 19:25:21.207058

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = '1cdb69cbdcaa'
down_revision = 'afedda6596b9'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_start', sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_asset_group_sighting_detection_start'),
            ['detection_start'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_group_sighting_detection_start'))
        batch_op.drop_column('detection_start')

    # ### end Alembic commands ###
