"""empty message

Revision ID: 1d3098a15e4f
Revises: daf15d36661f
Create Date: 2021-01-08 14:28:48.403819

"""

# revision identifiers, used by Alembic.
revision = '1d3098a15e4f'
down_revision = 'daf15d36661f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('message_template', sa.String(), nullable=False),
    sa.Column('message_values', sa.JSON(), nullable=True),
    sa.Column('recipient_guid', app.extensions.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_guid'], ['user.guid'], name=op.f('fk_notification_recipient_guid_user')),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_recipient_guid'), ['recipient_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_recipient_guid'))

    op.drop_table('notification')
    # ### end Alembic commands ###
