# -*- coding: utf-8 -*-
"""empty message

Revision ID: 2022b01697e4
Revises: f19732b1101b
Create Date: 2022-08-24 22:47:51.007940

"""
import sqlalchemy as sa
from alembic import op

import app
import app.extensions

# revision identifiers, used by Alembic.
revision = '2022b01697e4'
down_revision = 'f19732b1101b'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task_user_assignment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('assigner_guid', app.extensions.GUID(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_mission_task_user_assignment_assigner_guid_user'),
            'user',
            ['assigner_guid'],
            ['guid'],
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task_user_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_mission_task_user_assignment_assigner_guid_user'),
            type_='foreignkey',
        )
        batch_op.drop_column('assigner_guid')

    # ### end Alembic commands ###
