"""empty message

Revision ID: 204c9bb3fcc8
Revises: 60224b2588fd
Create Date: 2021-03-11 15:41:24.486409

"""

# revision identifiers, used by Alembic.
revision = '204c9bb3fcc8'
down_revision = '60224b2588fd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('asset_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_guid'], ['asset.guid'], name=op.f('fk_annotation_asset_guid_asset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_annotation'))
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_asset_guid'), ['asset_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_asset_guid'))

    op.drop_table('annotation')
    # ### end Alembic commands ###
