# -*- coding: utf-8 -*-
"""empty message

Revision ID: 214ba937eadf
Revises: 13241dd1fd5b
Create Date: 2021-11-17 21:11:24.715282

"""
import sqlalchemy as sa
from alembic import op

import app
import app.extensions

# revision identifiers, used by Alembic.
revision = '214ba937eadf'
down_revision = '13241dd1fd5b'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'individual_merge_request_vote',
        sa.Column('request_id', app.extensions.GUID(), nullable=False),
        sa.Column('user_guid', app.extensions.GUID(), nullable=False),
        sa.Column('vote', sa.String(length=10), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_guid'],
            ['user.guid'],
            name=op.f('fk_individual_merge_request_vote_user_guid_user'),
        ),
        sa.PrimaryKeyConstraint(
            'request_id',
            'user_guid',
            'created',
            name=op.f('pk_individual_merge_request_vote'),
        ),
    )
    with op.batch_alter_table('individual_merge_request_vote', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_individual_merge_request_vote_created'),
            ['created'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_individual_merge_request_vote_request_id'),
            ['request_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_individual_merge_request_vote_user_guid'),
            ['user_guid'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_individual_merge_request_vote_vote'), ['vote'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_merge_request_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_merge_request_vote_vote'))
        batch_op.drop_index(batch_op.f('ix_individual_merge_request_vote_user_guid'))
        batch_op.drop_index(batch_op.f('ix_individual_merge_request_vote_request_id'))
        batch_op.drop_index(batch_op.f('ix_individual_merge_request_vote_created'))

    op.drop_table('individual_merge_request_vote')
    # ### end Alembic commands ###
