"""empty message

Revision ID: 2530e554b6e3
Revises: 3fc0b28658aa
Create Date: 2022-02-08 15:46:40.905837

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions




# revision identifiers, used by Alembic.
revision = '2530e554b6e3'
down_revision = '3fc0b28658aa'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_resolved')

    # ### end Alembic commands ###
