"""empty message

Revision ID: 276fd451f6b4
Revises: edaa4f9c6c21
Create Date: 2020-12-16 11:44:56.786102

"""

# revision identifiers, used by Alembic.
revision = '276fd451f6b4'
down_revision = 'edaa4f9c6c21'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_user_membership_enrollment',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('organization_guid', app.extensions.GUID(), nullable=False),
    sa.Column('user_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_guid'], ['organization.guid'], name=op.f('fk_organization_user_membership_enrollment_organization_guid_organization')),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], name=op.f('fk_organization_user_membership_enrollment_user_guid_user')),
    sa.PrimaryKeyConstraint('organization_guid', 'user_guid', name=op.f('pk_organization_user_membership_enrollment'))
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_guid', app.extensions.GUID(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('version')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('logo_guid')

    op.drop_table('organization_user_membership_enrollment')
    # ### end Alembic commands ###
