"""empty message

Revision ID: 2b1db4279cc3
Revises: d7e0afc92ce2
Create Date: 2021-01-06 11:19:53.585405

"""

# revision identifiers, used by Alembic.
revision = '2b1db4279cc3'
down_revision = 'd7e0afc92ce2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False))
        batch_op.alter_column('sighting_guid',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.alter_column('sighting_guid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('public')

    # ### end Alembic commands ###
