# -*- coding: utf-8 -*-
"""empty message

Revision ID: 2c9d119ac26b
Revises: 0d9a04dd3d5c
Create Date: 2023-07-26 17:43:50.465989

"""
# import sqlalchemy as sa
# import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '2c9d119ac26b'
down_revision = '0d9a04dd3d5c'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autogenerated_name', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f('uq_autogenerated_name_prefix'), ['prefix', 'type']
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autogenerated_name', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('uq_autogenerated_name_prefix'), type_='unique'
        )

    # ### end Alembic commands ###
