# -*- coding: utf-8 -*-
"""empty message

Revision ID: 2ef73ff71f0c
Revises: 9ff1b7326151
Create Date: 2021-12-17 02:10:05.796710

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '2ef73ff71f0c'
down_revision = '9ff1b7326151'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'complex_date_time',
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('datetime', sa.DateTime(), nullable=False),
        sa.Column('timezone', sa.String(), nullable=False),
        sa.Column(
            'specificity',
            sa.Enum('year', 'month', 'day', 'time', name='specificities'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_complex_date_time')),
    )
    with op.batch_alter_table('complex_date_time', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_complex_date_time_datetime'), ['datetime'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_complex_date_time_specificity'), ['specificity'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_complex_date_time_timezone'), ['timezone'], unique=False
        )

    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_name_creator_guid_user', type_='foreignkey')
        batch_op.drop_constraint('fk_name_individual_guid_individual', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_name_individual_guid_individual'),
            'individual',
            ['individual_guid'],
            ['guid'],
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_name_creator_guid_user'), 'user', ['creator_guid'], ['guid']
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_name_creator_guid_user'), type_='foreignkey'
        )
        batch_op.drop_constraint(
            batch_op.f('fk_name_individual_guid_individual'), type_='foreignkey'
        )
        batch_op.create_foreign_key(
            'fk_name_individual_guid_individual',
            'individual',
            ['individual_guid'],
            ['guid'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'fk_name_creator_guid_user',
            'user',
            ['creator_guid'],
            ['guid'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('complex_date_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complex_date_time_timezone'))
        batch_op.drop_index(batch_op.f('ix_complex_date_time_specificity'))
        batch_op.drop_index(batch_op.f('ix_complex_date_time_datetime'))

    op.drop_table('complex_date_time')

    # Remove the enums created as part of the upgrade above
    sa.Enum(name='specificities').drop(op.get_bind(), checkfirst=False)

    # ### end Alembic commands ###
