# -*- coding: utf-8 -*-
"""empty message

Revision ID: 329c594dd8d7
Revises: f5240055f6f0
Create Date: 2021-09-29 10:08:35.246908

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '329c594dd8d7'
down_revision = 'f5240055f6f0'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('sender_guid', app.extensions.GUID(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('sender_guid')

    # ### end Alembic commands ###
