# -*- coding: utf-8 -*-
"""empty message

Revision ID: 3badaaa870b5
Revises: 0d4a39233a8a
Create Date: 2022-07-21 18:08:59.622905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3badaaa870b5'
down_revision = '0d4a39233a8a'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_client', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'updated',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'indexed',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_client_created'), ['created'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_client_indexed'), ['indexed'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_client_updated'), ['updated'], unique=False
        )

    with op.batch_alter_table('oauth2_grant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'updated',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'indexed',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_grant_created'), ['created'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_grant_indexed'), ['indexed'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_grant_updated'), ['updated'], unique=False
        )

    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'updated',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'indexed',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_token_created'), ['created'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_token_indexed'), ['indexed'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_oauth2_token_updated'), ['updated'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_token_updated'))
        batch_op.drop_index(batch_op.f('ix_oauth2_token_indexed'))
        batch_op.drop_index(batch_op.f('ix_oauth2_token_created'))
        batch_op.drop_column('indexed')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('oauth2_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_grant_updated'))
        batch_op.drop_index(batch_op.f('ix_oauth2_grant_indexed'))
        batch_op.drop_index(batch_op.f('ix_oauth2_grant_created'))
        batch_op.drop_column('indexed')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('oauth2_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_client_updated'))
        batch_op.drop_index(batch_op.f('ix_oauth2_client_indexed'))
        batch_op.drop_index(batch_op.f('ix_oauth2_client_created'))
        batch_op.drop_column('indexed')
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
