"""empty message

Revision ID: 3c21643a83ec
Revises: fa952f537929
Create Date: 2021-06-07 19:17:04.977429

"""

# revision identifiers, used by Alembic.
revision = '3c21643a83ec'
down_revision = 'fa952f537929'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.Enum('identification', 'un_reviewed', 'processed', 'failed', name='sightingstage'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
