"""empty message

Revision ID: 3ed4d2760bae
Revises: d7e0afc92ce2
Create Date: 2020-12-22 14:04:36.974954

"""

# revision identifiers, used by Alembic.
revision = '3ed4d2760bae'
down_revision = 'd7e0afc92ce2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_encounter',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('project_guid', app.extensions.GUID(), nullable=False),
    sa.Column('encounter_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_guid'], ['encounter.guid'], name=op.f('fk_project_encounter_encounter_guid_encounter')),
    sa.ForeignKeyConstraint(['project_guid'], ['project.guid'], name=op.f('fk_project_encounter_project_guid_project')),
    sa.PrimaryKeyConstraint('project_guid', 'encounter_guid', name=op.f('pk_project_encounter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_encounter')
    # ### end Alembic commands ###
