"""sighting name

Revision ID: 49c704ff6fa9
Revises: 7d391a027bd4
Create Date: 2021-07-20 13:46:26.545335

"""

# revision identifiers, used by Alembic.
revision = '49c704ff6fa9'
down_revision = '7d391a027bd4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
