# -*- coding: utf-8 -*-
"""empty message

Revision ID: 4a23a43a395d
Revises: 2022b01697e4
Create Date: 2022-09-06 21:46:14.218994

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a23a43a395d'
down_revision = '2022b01697e4'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')
    # ### end Alembic commands ###
