"""empty message

Revision ID: 4af714e9ad5e
Revises: 9cd353263d84
Create Date: 2021-01-29 12:44:26.893332

"""

# revision identifiers, used by Alembic.
revision = '4af714e9ad5e'
down_revision = '9cd353263d84'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_guid', app.extensions.GUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_organization_owner_guid'), ['owner_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_organization_owner_guid_user'), 'user', ['owner_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_organization_owner_guid_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organization_owner_guid'))
        batch_op.drop_column('owner_guid')

    # ### end Alembic commands ###
