# -*- coding: utf-8 -*-
"""empty message

Revision ID: 4b2d7014d79e
Revises: b011bd72aadd
Create Date: 2021-08-16 19:26:54.317352

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '4b2d7014d79e'
down_revision = 'b011bd72aadd'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('string', sa.String(), nullable=True))
        batch_op.alter_column(
            'file_upload_guid', existing_type=app.extensions.GUID(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.alter_column(
            'file_upload_guid', existing_type=app.extensions.GUID(), nullable=False
        )
        batch_op.drop_column('string')

    # ### end Alembic commands ###
