# -*- coding: utf-8 -*-
"""empty message

Revision ID: 4b70e9af2070
Revises: 07655219aea3
Create Date: 2023-07-24 20:20:22.492547

"""
# import sqlalchemy as sa

# import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# import app

# import app.extensions

# revision identifiers, used by Alembic.
revision = '4b70e9af2070'
down_revision = '8083ed5f8d4f'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autogenerated_name', schema=None) as batch_op:
        batch_op.alter_column(
            'reference_guid', existing_type=postgresql.UUID(), nullable=False
        )
        batch_op.drop_index('ix_autogenerated_name_reference_guid')
        batch_op.create_index(
            batch_op.f('ix_autogenerated_name_reference_guid'),
            ['reference_guid'],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autogenerated_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autogenerated_name_reference_guid'))
        batch_op.create_index(
            'ix_autogenerated_name_reference_guid', ['reference_guid'], unique=False
        )
        batch_op.alter_column(
            'reference_guid', existing_type=postgresql.UUID(), nullable=True
        )

    # ### end Alembic commands ###
