# -*- coding: utf-8 -*-
"""remove_annot_jobs

Revision ID: 52af6deb082b
Revises: 47a80ead3a90
Create Date: 2022-01-14 17:48:10.807644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52af6deb082b'
down_revision = '47a80ead3a90'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('jobs')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('jobs', sa.JSON(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
