"""empty message

Revision ID: 56ce9dfdbf4f
Revises: edaa4f9c6c21
Create Date: 2020-12-10 09:32:22.097537

"""

# revision identifiers, used by Alembic.
revision = '56ce9dfdbf4f'
down_revision = 'edaa4f9c6c21'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdDate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logoGuid', app.extensions.GUID(), nullable=True))
        batch_op.add_column(sa.Column('logoUrl', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('modifiedDate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('version')
        batch_op.drop_column('modifiedDate')
        batch_op.drop_column('logoUrl')
        batch_op.drop_column('logoGuid')
        batch_op.drop_column('createdDate')

    # ### end Alembic commands ###
