"""empty message

Revision ID: 5854c14c634d
Revises: df3abf8d2071
Create Date: 2021-01-29 16:47:00.842610

"""

# revision identifiers, used by Alembic.
revision = '5854c14c634d'
down_revision = 'df3abf8d2071'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_assets',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('encounter_guid', app.extensions.GUID(), nullable=False),
    sa.Column('asset_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_guid'], ['asset.guid'], name=op.f('fk_encounter_assets_asset_guid_asset')),
    sa.ForeignKeyConstraint(['encounter_guid'], ['encounter.guid'], name=op.f('fk_encounter_assets_encounter_guid_encounter')),
    sa.PrimaryKeyConstraint('encounter_guid', 'asset_guid', name=op.f('pk_encounter_assets'))
    )
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounter_assets')
    # ### end Alembic commands ###
