"""empty message

Revision ID: 60224b2588fd
Revises: ae7ea9e66e45
Create Date: 2021-03-10 14:49:21.520097

"""

# revision identifiers, used by Alembic.
revision = '60224b2588fd'
down_revision = 'ae7ea9e66e45'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_upload',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_file_upload'))
    )
    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_upload_mime_type'), ['mime_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_upload_mime_type'))

    op.drop_table('file_upload')
    # ### end Alembic commands ###
