"""Create SiteSettings

Revision ID: 62964b09ea91
Revises: 7bbe8c4053f3
Create Date: 2021-04-05 13:41:45.369265

"""

# revision identifiers, used by Alembic.
revision = '62964b09ea91'
down_revision = '7bbe8c4053f3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_setting',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('file_upload_guid', app.extensions.GUID(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.ForeignKeyConstraint(['file_upload_guid'], ['file_upload.guid'], name=op.f('fk_site_setting_file_upload_guid_file_upload'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_site_setting'))
    )
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_setting')
    # ### end Alembic commands ###
