# -*- coding: utf-8 -*-
"""empty message

Revision ID: 65f9621bd3dd
Revises: f788098878ac
Create Date: 2022-05-13 10:30:15.136596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65f9621bd3dd'
down_revision = 'f788098878ac'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
