# -*- coding: utf-8 -*-
"""empty message

Revision ID: 66bbd28297d2
Revises: 4a23a43a395d
Create Date: 2022-10-07 18:12:05.644149

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66bbd28297d2'
down_revision = '4a23a43a395d'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    with op.batch_alter_table('mission_task_user_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_mission_task_user_assignment_assigner_guid_user', type_='foreignkey'
        )
        batch_op.drop_column('assigner_guid')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_task_user_assignment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'assigner_guid', postgresql.UUID(), autoincrement=False, nullable=False
            )
        )
        batch_op.create_foreign_key(
            'fk_mission_task_user_assignment_assigner_guid_user',
            'user',
            ['assigner_guid'],
            ['guid'],
        )

    with op.batch_alter_table('mission_task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
