"""empty message

Revision ID: 6ddd7dbd2138
Revises: 8bea1f7d2e44
Create Date: 2021-05-24 15:55:07.285110

"""

# revision identifiers, used by Alembic.
revision = '6ddd7dbd2138'
down_revision = '8bea1f7d2e44'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_control',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('asset_group_sighting_uuid', app.extensions.GUID(), nullable=True),
    sa.Column('sighting_uuid', app.extensions.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_job_control'))
    )
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('jobs')

    op.drop_table('job_control')
    # ### end Alembic commands ###
