"""Remove user footer_logo

Revision ID: 757715188c2f
Revises: 60224b2588fd
Create Date: 2021-03-15 19:36:17.040454

"""

# revision identifiers, used by Alembic.
revision = '757715188c2f'
down_revision = '60224b2588fd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions

from sqlalchemy.dialects import postgresql

def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('footer_logo_asset_guid')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footer_logo_asset_guid', postgresql.UUID(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
