"""empty message

Revision ID: 79de35f6e61c
Revises: 001eedbc2f9a
Create Date: 2021-10-19 10:11:07.099309

"""

# revision identifiers, used by Alembic.
revision = '79de35f6e61c'
down_revision = '001eedbc2f9a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_social_group'))
    )
    op.create_table('social_group_individual_membership',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('group_guid', app.extensions.GUID(), nullable=False),
    sa.Column('individual_guid', app.extensions.GUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_guid'], ['social_group.guid'], name=op.f('fk_social_group_individual_membership_group_guid_social_group')),
    sa.ForeignKeyConstraint(['individual_guid'], ['individual.guid'], name=op.f('fk_social_group_individual_membership_individual_guid_individual')),
    sa.PrimaryKeyConstraint('group_guid', 'individual_guid', name=op.f('pk_social_group_individual_membership'))
    )
    with op.batch_alter_table('social_group_individual_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_group_individual_membership_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_group_individual_membership_updated'), ['updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_group_individual_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_group_individual_membership_updated'))
        batch_op.drop_index(batch_op.f('ix_social_group_individual_membership_created'))

    op.drop_table('social_group_individual_membership')
    op.drop_table('social_group')
    # ### end Alembic commands ###
