"""empty message

Revision ID: 7bbe8c4053f3
Revises: de90a1cd0eb2
Create Date: 2021-04-08 11:17:45.083596

"""

# revision identifiers, used by Alembic.
revision = '7bbe8c4053f3'
down_revision = 'de90a1cd0eb2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_guid', app.extensions.GUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_annotation_encounter_guid'), ['encounter_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_annotation_encounter_guid_encounter'), 'encounter', ['encounter_guid'], ['guid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_annotation_encounter_guid_encounter'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_annotation_encounter_guid'))
        batch_op.drop_column('encounter_guid')

    # ### end Alembic commands ###
