# -*- coding: utf-8 -*-
"""empty message

Revision ID: 7d391a027bd4
Revises: a7396fa56571
Create Date: 2021-07-01 09:11:57.821816

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = '7d391a027bd4'
down_revision = 'a7396fa56571'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs', app.extensions.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ia_configs', app.extensions.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('ia_configs')
        batch_op.drop_column('jobs')

    # ### end Alembic commands ###
