"""empty message

Revision ID: 88244eed06d0
Revises: 2ef73ff71f0c
Create Date: 2021-12-20 20:08:32.545465

"""

# revision identifiers, used by Alembic.
revision = '88244eed06d0'
down_revision = '2ef73ff71f0c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_guid', app.extensions.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_encounter_time_guid'), ['time_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_encounter_time_guid_complex_date_time'), 'complex_date_time', ['time_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_encounter_time_guid_complex_date_time'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_encounter_time_guid'))
        batch_op.drop_column('time_guid')

    # ### end Alembic commands ###
