"""empty message

Revision ID: 8a8e855a787a
Revises: 276fd451f6b4
Create Date: 2020-12-17 16:53:24.332578

"""

# revision identifiers, used by Alembic.
revision = '8a8e855a787a'
down_revision = '276fd451f6b4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', app.extensions.GUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
