"""empty message

Revision ID: 8bd225ec538b
Revises: 060344b8b804
Create Date: 2021-01-22 09:18:10.569847

"""

# revision identifiers, used by Alembic.
revision = '8bd225ec538b'
down_revision = '060344b8b804'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
