"""empty message

Revision ID: 99b2ab9e9970
Revises: 15afb6859894
Create Date: 2021-03-18 16:06:14.178486

"""

# revision identifiers, used by Alembic.
revision = '99b2ab9e9970'
down_revision = '15afb6859894'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
