"""empty message

Revision ID: 9cd353263d84
Revises: 06364a7a31be
Create Date: 2021-01-29 07:35:03.058401

"""

# revision identifiers, used by Alembic.
revision = '9cd353263d84'
down_revision = '06364a7a31be'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_user_moderator_enrollment',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('organization_guid', app.extensions.GUID(), nullable=False),
    sa.Column('user_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_guid'], ['organization.guid'], name=op.f('fk_organization_user_moderator_enrollment_organization_guid_organization')),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], name=op.f('fk_organization_user_moderator_enrollment_user_guid_user')),
    sa.PrimaryKeyConstraint('organization_guid', 'user_guid', name=op.f('pk_organization_user_moderator_enrollment'))
    )
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_user_moderator_enrollment')
    # ### end Alembic commands ###
