# -*- coding: utf-8 -*-
"""empty message

Revision ID: 9e4beb159ecb
Revises: 23b9e51a7f2e
Create Date: 2022-05-05 21:50:43.471199

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9e4beb159ecb'
down_revision = '23b9e51a7f2e'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_asset_group_progress_preparation_guid_progress', type_='foreignkey'
        )
        batch_op.drop_column('progress_preparation_guid')

    with op.batch_alter_table('git_store', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('progress_preparation_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_git_store_progress_preparation_guid_progress'),
            'progress',
            ['progress_preparation_guid'],
            ['guid'],
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_store', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_git_store_progress_preparation_guid_progress'),
            type_='foreignkey',
        )
        batch_op.drop_column('progress_preparation_guid')

    with op.batch_alter_table('asset_group', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'progress_preparation_guid',
                postgresql.UUID(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            'fk_asset_group_progress_preparation_guid_progress',
            'progress',
            ['progress_preparation_guid'],
            ['guid'],
        )

    # ### end Alembic commands ###
