# -*- coding: utf-8 -*-
"""empty message

Revision ID: 9e71ecc2708a
Revises: 9b2a1efceeec
Create Date: 2021-05-27 20:19:49.829026

"""
from alembic import op

import app
import app.extensions

# revision identifiers, used by Alembic.
revision = '9e71ecc2708a'
down_revision = '9b2a1efceeec'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.alter_column(
            'encounter_guid', existing_type=app.extensions.GUID(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.alter_column(
            'encounter_guid', existing_type=app.extensions.GUID(), nullable=False
        )

    # ### end Alembic commands ###
