"""empty message

Revision ID: a06c8c4f2d82
Revises: 69accf38d040
Create Date: 2020-12-06 10:52:45.690275

"""

# revision identifiers, used by Alembic.
revision = 'a06c8c4f2d82'
down_revision = '69accf38d040'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index('ix_organization_user_guid')
        batch_op.drop_constraint('fk_organization_user_guid_user', type_='foreignkey')
        batch_op.drop_column('user_guid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_guid', app.extensions.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_organization_guid'), ['organization_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_organization_guid_organization'), 'organization', ['organization_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_organization_guid_organization'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_organization_guid'))
        batch_op.drop_column('organization_guid')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_guid', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key('fk_organization_user_guid_user', 'user', ['user_guid'], ['guid'], ondelete='CASCADE')
        batch_op.create_index('ix_organization_user_guid', ['user_guid'], unique=False)

    # ### end Alembic commands ###
