"""empty message

Revision ID: a9a123deb063
Revises: edaa4f9c6c21
Create Date: 2020-12-11 12:18:51.411810

"""

# revision identifiers, used by Alembic.
revision = 'a9a123deb063'
down_revision = 'edaa4f9c6c21'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_guid', app.extensions.GUID(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_guid', app.extensions.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_organization_guid'), ['organization_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_organization_guid_organization'), 'organization', ['organization_guid'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_organization_guid_organization'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_organization_guid'))
        batch_op.drop_column('organization_guid')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('version')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('logo_guid')

    # ### end Alembic commands ###
