# -*- coding: utf-8 -*-
"""empty message

Revision ID: aa17b88d4744
Revises: ed7b9eb99d21
Create Date: 2022-04-27 23:47:59.183346

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils  # noqa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = 'aa17b88d4744'
down_revision = 'ed7b9eb99d21'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'intelligent_agent_content',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('indexed', sa.DateTime(), nullable=False),
        sa.Column('viewed', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('agent_type', sa.String(length=128), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'intake',
                'rejected',
                'active',
                'active_detection',
                'active_identification',
                'complete',
                'error',
                name='intelligentagentcontentstate',
            ),
            nullable=False,
        ),
        sa.Column('owner_guid', app.extensions.GUID(), nullable=True),
        sa.Column('source', app.extensions.JSON(), nullable=False),
        sa.Column('raw_content', app.extensions.JSON(), nullable=False),
        sa.Column('data', app.extensions.JSON(), nullable=True),
        sa.Column('asset_group_guid', app.extensions.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['asset_group_guid'],
            ['asset_group.guid'],
            name=op.f('fk_intelligent_agent_content_asset_group_guid_asset_group'),
        ),
        sa.ForeignKeyConstraint(
            ['owner_guid'],
            ['user.guid'],
            name=op.f('fk_intelligent_agent_content_owner_guid_user'),
        ),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_intelligent_agent_content')),
    )
    with op.batch_alter_table('intelligent_agent_content', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_agent_type'),
            ['agent_type'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_asset_group_guid'),
            ['asset_group_guid'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_created'), ['created'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_indexed'), ['indexed'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_owner_guid'),
            ['owner_guid'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_state'), ['state'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_intelligent_agent_content_updated'), ['updated'], unique=False
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('linked_accounts', app.extensions.JSON(), nullable=True)
        )
        batch_op.add_column(sa.Column('twitter_username', sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f('uq_user_twitter_username'), ['twitter_username']
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_twitter_username'), type_='unique')
        batch_op.drop_column('twitter_username')
        batch_op.drop_column('linked_accounts')

    with op.batch_alter_table('intelligent_agent_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_updated'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_state'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_owner_guid'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_indexed'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_created'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_asset_group_guid'))
        batch_op.drop_index(batch_op.f('ix_intelligent_agent_content_agent_type'))

    op.drop_table('intelligent_agent_content')
    # ### end Alembic commands ###
