# -*- coding: utf-8 -*-
"""notification_preferences

Revision ID: b011bd72aadd
Revises: d4b6b2afa11d
Create Date: 2021-08-16 18:40:24.897375

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = 'b011bd72aadd'
down_revision = 'd4b6b2afa11d'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'system_notification_preferences',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('viewed', sa.DateTime(), nullable=False),
        sa.Column('preferences', app.extensions.JSON(), nullable=True),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_system_notification_preferences')),
    )
    op.create_table(
        'user_notification_preferences',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('viewed', sa.DateTime(), nullable=False),
        sa.Column('preferences', app.extensions.JSON(), nullable=True),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('digest', sa.Boolean(), nullable=False),
        sa.Column('user_guid', app.extensions.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_guid'],
            ['user.guid'],
            name=op.f('fk_user_notification_preferences_user_guid_user'),
        ),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_user_notification_preferences')),
    )
    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_notification_preferences_user_guid'),
            ['user_guid'],
            unique=False,
        )

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(), nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('message_template')

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'message_template', sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                'timestamp',
                sa.DateTime(),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column('message_type')

    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_user_guid'))

    op.drop_table('user_notification_preferences')
    op.drop_table('system_notification_preferences')
    # ### end Alembic commands ###
