# -*- coding: utf-8 -*-
"""empty message

Revision ID: caf961b9ac34
Revises: 32145d0959ae
Create Date: 2021-09-09 14:51:16.383863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf961b9ac34'
down_revision = '32145d0959ae'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_user_associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_initiator', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_user_associations', schema=None) as batch_op:
        batch_op.drop_column('edit_initiator')

    # ### end Alembic commands ###
