# -*- coding: utf-8 -*-
"""empty message

Revision ID: cc1f915cde87
Revises: ce5c26b34f15
Create Date: 2022-05-05 19:33:23.318457

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = 'cc1f915cde87'
down_revision = '65f9621bd3dd'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'progress',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('description', sa.String(length=256), nullable=False),
        sa.Column('percentage', sa.Integer(), nullable=True),
        sa.Column('eta', sa.Float(), nullable=True),
        sa.Column('celery_guid', app.extensions.GUID(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'created',
                'healthy',
                'completed',
                'cancelled',
                'failed',
                name='progressstatus',
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            'percentage <= 100', name=op.f('ck_progress_progress_percentage_range_max')
        ),
        sa.CheckConstraint(
            'percentage >= 0', name=op.f('ck_progress_progress_percentage_range_min')
        ),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_progress')),
    )

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE assetgroupsightingstage ADD VALUE 'preparation'")

    with op.batch_alter_table('git_store', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('progress_preparation_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_git_store_progress_preparation_guid_progress'),
            'progress',
            ['progress_preparation_guid'],
            ['guid'],
        )
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_store', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_git_store_progress_preparation_guid_progress',
            type_='foreignkey',
        )
        batch_op.drop_column('progress_preparation_guid')

    op.drop_table('progress')

    sa.Enum(name='progressstatus').drop(op.get_bind(), checkfirst=False)

    conn.execute(
        sa.sql.text(
            """
            UPDATE asset_group_sighting
            SET stage = 'unknown'
            WHERE stage = 'preparation'
            """
        )
    )

    op.execute('ALTER TYPE assetgroupsightingstage RENAME TO assetgroupsightingstage_old')
    op.execute(
        "CREATE TYPE assetgroupsightingstage AS ENUM('unknown', 'detection', 'curation', 'processed', 'failed')"
    )
    op.execute(
        (
            'ALTER TABLE asset_group_sighting ALTER COLUMN stage TYPE assetgroupsightingstage USING '
            'stage::text::assetgroupsightingstage'
        )
    )
    op.execute('DROP TYPE assetgroupsightingstage_old')
    # ### end Alembic commands ###
