# -*- coding: utf-8 -*-
"""empty message

Revision ID: cc1f915cde87
Revises: ce5c26b34f15
Create Date: 2022-05-05 19:33:23.318457

"""
from alembic import op
import sqlalchemy as sa

import app
import app.extensions


# revision identifiers, used by Alembic.
revision = 'cc1f915cde87'
down_revision = 'ce5c26b34f15'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'progress',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('description', sa.String(length=50), nullable=False),
        sa.Column('percentage', sa.Integer(), nullable=True),
        sa.CheckConstraint(
            'percentage <= 100', name=op.f('ck_progress_progress_percentage_range_max')
        ),
        sa.CheckConstraint(
            'percentage >= 0', name=op.f('ck_progress_progress_percentage_range_min')
        ),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_progress')),
    )
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    # ### end Alembic commands ###
