"""adding_social_groups

Revision ID: d52ebe97d5e5
Revises: 001eedbc2f9a
Create Date: 2021-10-22 10:27:59.639315

"""

# revision identifiers, used by Alembic.
revision = 'd52ebe97d5e5'
down_revision = '001eedbc2f9a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_social_group'))
    )
    with op.batch_alter_table('social_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_group_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_group_updated'), ['updated'], unique=False)

    op.create_table('social_group_individual_membership',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('group_guid', app.extensions.GUID(), nullable=False),
    sa.Column('individual_guid', app.extensions.GUID(), nullable=False),
    sa.Column('roles', app.extensions.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_guid'], ['social_group.guid'], name=op.f('fk_social_group_individual_membership_group_guid_social_group')),
    sa.ForeignKeyConstraint(['individual_guid'], ['individual.guid'], name=op.f('fk_social_group_individual_membership_individual_guid_individual')),
    sa.PrimaryKeyConstraint('group_guid', 'individual_guid', name=op.f('pk_social_group_individual_membership'))
    )
    with op.batch_alter_table('social_group_individual_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_group_individual_membership_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_group_individual_membership_updated'), ['updated'], unique=False)

    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', app.extensions.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('social_group_individual_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_group_individual_membership_updated'))
        batch_op.drop_index(batch_op.f('ix_social_group_individual_membership_created'))

    op.drop_table('social_group_individual_membership')
    with op.batch_alter_table('social_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_group_updated'))
        batch_op.drop_index(batch_op.f('ix_social_group_created'))

    op.drop_table('social_group')
    # ### end Alembic commands ###
