"""empty message

Revision ID: d5cd14a27210
Revises: fe1a5f56d6c1
Create Date: 2021-04-29 18:21:36.951885

"""

# revision identifiers, used by Alembic.
revision = 'd5cd14a27210'
down_revision = 'fe1a5f56d6c1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_group_sighting',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('stage', sa.Enum('unknown', 'detection', 'curation', 'committed', 'processed', name='assetgroupsightingstage'), nullable=False),
    sa.Column('owner_guid', app.extensions.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_guid'], ['asset_group.guid'], name=op.f('fk_asset_group_sighting_owner_guid_asset_group')),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_asset_group_sighting'))
    )
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_group_sighting_owner_guid'), ['owner_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_group_sighting_owner_guid'))

    op.drop_table('asset_group_sighting')
    # ### end Alembic commands ###
