# -*- coding: utf-8 -*-
"""empty message

Revision ID: dc91b517a7a4
Revises: 53b0fec87272
Create Date: 2024-01-22 22:51:34.690766

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'dc91b517a7a4'
down_revision = '53b0fec87272'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_keywords', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_annotation_keywords_keyword_guid_keyword', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_annotation_keywords_keyword_guid_keyword'),
            'keyword',
            ['keyword_guid'],
            ['guid'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_tags_tag_guid_keyword', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_asset_tags_tag_guid_keyword'),
            'keyword',
            ['tag_guid'],
            ['guid'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_asset_tags_tag_guid_keyword'), type_='foreignkey'
        )
        batch_op.create_foreign_key(
            'fk_asset_tags_tag_guid_keyword', 'keyword', ['tag_guid'], ['guid']
        )

    with op.batch_alter_table('annotation_keywords', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_annotation_keywords_keyword_guid_keyword'), type_='foreignkey'
        )
        batch_op.create_foreign_key(
            'fk_annotation_keywords_keyword_guid_keyword',
            'keyword',
            ['keyword_guid'],
            ['guid'],
        )

    # ### end Alembic commands ###
