"""add version to individual

Revision ID: de90a1cd0eb2
Revises: 04a5695ac4a2
Create Date: 2021-04-02 15:35:53.821625

"""

# revision identifiers, used by Alembic.
revision = 'de90a1cd0eb2'
down_revision = '04a5695ac4a2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
