"""empty message

Revision ID: df3abf8d2071
Revises: 06364a7a31be
Create Date: 2021-01-27 17:12:58.385684

"""

# revision identifiers, used by Alembic.
revision = 'df3abf8d2071'
down_revision = '06364a7a31be'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration_user_associations',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('collaboration_guid', app.extensions.GUID(), nullable=False),
    sa.Column('user_guid', app.extensions.GUID(), nullable=False),
    sa.Column('initiator', sa.Boolean(), nullable=False),
    sa.Column('read_approval_state', sa.String(length=32), nullable=False),
    sa.Column('edit_approval_state', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_guid'], ['collaboration.guid'], name=op.f('fk_collaboration_user_associations_collaboration_guid_collaboration')),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], name=op.f('fk_collaboration_user_associations_user_guid_user')),
    sa.PrimaryKeyConstraint('collaboration_guid', 'user_guid', name=op.f('pk_collaboration_user_associations'))
    )
    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('collaboration_user_associations')
    # ### end Alembic commands ###
