# -*- coding: utf-8 -*-
"""empty message

Revision ID: e79a100e0252
Revises: 1cdb69cbdcaa
Create Date: 2022-06-24 14:07:33.184539

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e79a100e0252'
down_revision = '1cdb69cbdcaa'


def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.alter_column(
            'curation_start',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.alter_column(
            'curation_start',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )

    # ### end Alembic commands ###
