"""empty message

Revision ID: edaa4f9c6c21
Revises: a8fb9085da79
Create Date: 2020-11-20 15:45:57.692735

"""

# revision identifiers, used by Alembic.
revision = 'edaa4f9c6c21'
down_revision = 'a8fb9085da79'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=False))
        batch_op.alter_column('magic_signature',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_asset_path'), ['path'], unique=False)

    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.DateTime(), nullable=True))
        batch_op.alter_column('viewed', nullable=False)

    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.DateTime(), nullable=True))
        batch_op.alter_column('viewed', nullable=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.DateTime(), nullable=True))
        batch_op.alter_column('viewed', nullable=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('viewed')

    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.drop_column('viewed')

    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.drop_column('viewed')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_path'))
        batch_op.alter_column('magic_signature',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('path')

    # ### end Alembic commands ###
