"""JobControl

Revision ID: f2d512a7ccdd
Revises: 9e71ecc2708a
Create Date: 2021-06-01 15:32:32.996776

"""

# revision identifiers, used by Alembic.
revision = 'f2d512a7ccdd'
down_revision = '9e71ecc2708a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_control',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('asset_group_sighting_uuid', app.extensions.GUID(), nullable=True),
    sa.Column('annotation_uuid', app.extensions.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_job_control'))
    )
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('jobs')

    op.drop_table('job_control')
    # ### end Alembic commands ###
