"""empty message

Revision ID: fca2aa76992c
Revises: dce7d7e06b22
Create Date: 2020-12-17 17:07:34.019867

"""

# revision identifiers, used by Alembic.
revision = 'fca2aa76992c'
down_revision = 'dce7d7e06b22'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sighting',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_sighting'))
    )
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sighting_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_encounter_sighting_id_sighting'), 'sighting', ['sighting_id'], ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_encounter_sighting_id_sighting'), type_='foreignkey')
        batch_op.drop_column('sighting_id')

    op.drop_table('sighting')
    # ### end Alembic commands ###
