"""addition of AssetGroupSightings tables

Revision ID: fd6c099190c9
Revises: 3c74d2d3214a_initial_database
Create Date: 2021-05-06 18:39:29.140862

"""

# revision identifiers, used by Alembic.
revision = 'fd6c099190c9'
down_revision = '3c74d2d3214a_initial_database'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    """
    Upgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    AssetGroupSightingStage = sa.Enum('unknown', 'detection', 'curation', 'committed', 'processed', 'failed', name="assetgroupsightingstage")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_group_sighting',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('owner_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_guid'], ['asset_group.guid'], name=op.f('fk_asset_group_sighting_owner_guid_asset_group')),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_asset_group_sighting'))
    )
    op.add_column('asset_group_sighting', sa.Column('stage', AssetGroupSightingStage, nullable=False))
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_group_sighting_owner_guid'), ['owner_guid'], unique=False)

    op.create_table('asset_group_job',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('owner_guid', app.extensions.GUID(), nullable=False),
    sa.Column('jobId', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_guid'], ['asset_group_sighting.guid'], name=op.f('fk_asset_group_job_owner_guid_asset_group_sighting')),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_asset_group_job'))
    )
    op.add_column('asset_group_job', sa.Column('stage', AssetGroupSightingStage, nullable=False))
    with op.batch_alter_table('asset_group_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_group_job_owner_guid'), ['owner_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade Semantic Description:
        ENTER DESCRIPTION HERE
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_group_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_group_job_owner_guid'))

    op.drop_table('asset_group_job')
    with op.batch_alter_table('asset_group_sighting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_group_sighting_owner_guid'))

    op.drop_table('asset_group_sighting')
    # ### end Alembic commands ###
