# -*- coding: utf-8 -*-
"""
Input arguments (Parameters) for Autogeneratednames resources RESTful API
-----------------------------------------------------------
"""

from flask_marshmallow import base_fields

from flask_restx_patched import Parameters, PatchJSONParameters

from . import schemas


class CreateAutogeneratedNameParameters(
    Parameters, schemas.DetailedAutogeneratedNameSchema
):
    reference_guid = base_fields.UUID(
        description='The GUID of the any referenece', required=False
    )
    type = base_fields.String(
        description='Type of AutogeneratedName, must be "species" ', required=True
    )
    prefix = base_fields.String(
        description='The prefix to use in the name', required=True
    )
    start_value = base_fields.Integer(description='Value to start at', required=False)

    class Meta(schemas.DetailedAutogeneratedNameSchema.Meta):
        pass


class PatchAutogeneratedNameDetailsParameters(PatchJSONParameters):
    # pylint: disable=abstract-method,missing-docstring
    OPERATION_CHOICES = (PatchJSONParameters.OP_REPLACE,)

    PATH_CHOICES = tuple()
