# -*- coding: utf-8 -*-
"""
Serialization schemas for AutogeneratedNames resources RESTful API
----------------------------------------------------
"""


from flask_restx_patched import ModelSchema

from .models import AutogeneratedName


class BaseAutogeneratedNameSchema(ModelSchema):
    """
    Base AutogeneratedName schema exposes only the most general fields.
    """

    class Meta:
        # pylint: disable=missing-docstring
        model = AutogeneratedName
        fields = (AutogeneratedName.guid.key,)
        dump_only = (AutogeneratedName.guid.key,)


class DetailedAutogeneratedNameSchema(BaseAutogeneratedNameSchema):
    """
    Detailed AutogeneratedName schema exposes all useful fields.
    """

    class Meta(BaseAutogeneratedNameSchema.Meta):
        fields = BaseAutogeneratedNameSchema.Meta.fields + (
            AutogeneratedName.created.key,
            AutogeneratedName.updated.key,
            AutogeneratedName.type.key,
            AutogeneratedName.prefix.key,
            AutogeneratedName.reference_guid.key,
            AutogeneratedName.next_value.key,
        )
        dump_only = BaseAutogeneratedNameSchema.Meta.dump_only + (
            AutogeneratedName.created.key,
            AutogeneratedName.updated.key,
        )
