# -*- coding: utf-8 -*-
# pylint: disable=missing-docstring

import pytest

import tests.modules.autogen_names.resources.utils as auto_name_utils
from tests.utils import module_unavailable


@pytest.mark.skipif(
    module_unavailable('autogenerated_names'),
    reason='Autogenerated names module disabled',
)
def test_create_autogenerated_name(
    flask_app_client,
    researcher_1,
    admin_user,
    researcher_2,
    user_manager_user,
    db,
    request,
    test_root,
):

    import uuid

    import tests.modules.individuals.resources.utils as individual_utils

    request.addfinalizer(lambda: auto_name_utils.clear_autogen(flask_app_client))
    individual1_uuids = individual_utils.create_individual_and_sighting(
        flask_app_client,
        researcher_1,
        request,
        test_root,
    )
    individual1_id = individual1_uuids['individual']
    individual1_data = individual_utils.read_individual(  # NOQA
        flask_app_client, researcher_1, individual1_id
    ).json
    auto_name_utils.read_all_autogen_names(flask_app_client, admin_user)
    auto_name_utils.read_all_autogen_names(flask_app_client, researcher_1)
    data = {
        str(uuid.uuid4()): {
            'prefix': 'woo',
            'type': 'auto_species',
            'enabled': True,
            'reference_guid': individual1_data['taxonomy'],
        }
    }
    auto_name_utils.create_autogen_name(flask_app_client, admin_user, data)

    # create another one the same, should fail
    new_data = {str(uuid.uuid4()): {'prefix': 'woo', 'type': 'auto_species'}}
    error = 'All autogenerated names need type, prefix, and reference_guid'
    auto_name_utils.create_autogen_name(
        flask_app_client, admin_user, new_data, 400, error
    )

    names = auto_name_utils.read_all_autogen_names(flask_app_client, admin_user)
    spec_woos = [
        names[name_guid]
        for name_guid in names
        if names[name_guid]['type'] == 'auto_species'
        and names[name_guid]['prefix'] == 'woo'
    ]
    assert len(spec_woos) == 1
    name = spec_woos[0]
    assert name['type'] == 'auto_species'
    assert name['prefix'] == 'woo'

    individual2_uuids = individual_utils.create_individual_and_sighting(
        flask_app_client,
        researcher_1,
        request,
        test_root,
    )
    individual2_id = individual2_uuids['individual']  # NOQA
    individual2_data = individual_utils.read_individual(  # NOQA
        flask_app_client, researcher_1, individual1_id
    ).json


@pytest.mark.skipif(
    module_unavailable('autogenerated_names'),
    reason='Autogenerated names module disabled',
)
def test_create_individual(
    flask_app_client,
    researcher_1,
    admin_user,
    researcher_2,
    user_manager_user,
    db,
    request,
    test_root,
):

    import uuid

    import tests.modules.individuals.resources.utils as individual_utils
    from app.modules.autogenerated_names.models import AutogeneratedName
    from app.modules.individuals.models import Individual

    request.addfinalizer(lambda: auto_name_utils.clear_autogen(flask_app_client))
    individual_uuids = individual_utils.create_individual_and_sighting(
        flask_app_client,
        researcher_1,
        request,
        test_root,
    )
    individual_id = individual_uuids['individual']
    individual_data = individual_utils.read_individual(  # NOQA
        flask_app_client, researcher_1, individual_id
    ).json
    assert len(individual_data['names']) == 0
    individual = Individual.query.get(individual_id)
    assert individual
    assert len(individual.names) == 0

    agn_prefix = 'FOO'
    agn_guid = str(uuid.uuid4())
    agn_guid2 = str(uuid.uuid4())
    data = {
        agn_guid: {
            'prefix': agn_prefix,
            'type': 'auto_species',
            'enabled': True,
            'reference_guid': individual_data['taxonomy'],
        },
        agn_guid2: {
            'prefix': agn_prefix,
            'type': 'auto_species',
            'enabled': True,
            'reference_guid': individual_data['taxonomy'],
        },
    }
    # should be disallowed due to duplicate reference_guid above
    rtn = auto_name_utils.create_autogen_name(
        flask_app_client, admin_user, data, expected_status_code=400
    )
    assert 'appears in both' in rtn.json['message']

    # now test missing type
    del data[agn_guid2]
    del data[agn_guid]['type']
    rtn = auto_name_utils.create_autogen_name(
        flask_app_client, admin_user, data, expected_status_code=400
    )
    assert 'All autogenerated names need' in rtn.json['message']

    # now bad type
    data[agn_guid]['type'] = 'fubarrrrr'
    rtn = auto_name_utils.create_autogen_name(
        flask_app_client, admin_user, data, expected_status_code=400
    )
    assert 'not supported' in rtn.json['message']

    # now this should work
    data[agn_guid]['type'] = 'auto_species'
    auto_name_utils.create_autogen_name(flask_app_client, admin_user, data)

    agns = auto_name_utils.read_all_autogen_names(flask_app_client, admin_user)
    assert agn_guid in agns

    # above should have autopopulated names for indivs
    assert len(individual.names) == 1
    assert individual.names[0].context == f'autogen-{agn_guid}'
    assert individual.names[0].value == '0000'
    assert individual.names[0].value_resolved == f'{agn_prefix}-0000'

    # check the counter
    agn = AutogeneratedName.query.get(agn_guid)
    assert agn
    n = agn.get_next()
    assert n == '0001'
    n = agn.get_next()
    assert n == '0002'
    n = agn.get_next()
    assert n == '0003'


def test_config(
    flask_app_client,
    researcher_1,
    admin_user,
    researcher_2,
    user_manager_user,
    db,
    request,
    test_root,
):

    import uuid

    import tests.modules.individuals.resources.utils as individual_utils
    import tests.modules.site_settings.resources.utils as setting_utils

    # from app.modules.autogenerated_names.models import AutogeneratedName
    # from app.modules.individuals.models import Individual

    request.addfinalizer(lambda: auto_name_utils.clear_autogen(flask_app_client))
    individual1_uuids = individual_utils.create_individual_and_sighting(
        flask_app_client,
        researcher_1,
        request,
        test_root,
    )
    individual1_id = individual1_uuids['individual']
    individual1_data = individual_utils.read_individual(  # NOQA
        flask_app_client, researcher_1, individual1_id
    ).json

    tx1_guid = individual1_data['taxonomy']
    agn_prefix = 'BAR'
    agn_guid = str(uuid.uuid4())
    data = {
        agn_guid: {
            'prefix': agn_prefix,
            'type': 'auto_species',
            'enabled': True,
            'reference_guid': tx1_guid,
        },
    }
    # this creates an autoname for tx1_guid
    auto_name_utils.create_autogen_name(
        flask_app_client,
        admin_user,
        data,
    )
    agns = auto_name_utils.read_all_autogen_names(flask_app_client, admin_user)
    # now lets add a new taxonomy to the mix
    #  note: this does nothing with AGN so it should reset above AGN to enabled=False
    assert agn_guid in agns
    assert agns[agn_guid]['enabled']
    vals = [
        {
            'id': tx1_guid,
            'commonNames': ['Example'],
            'scientificName': 'Exempli gratia',
            'itisTsn': -1234,
        },
        {
            'commonNames': ['Example'],
            'scientificName': 'Exempli gratia deux',
            'itisTsn': -1235,
        },
    ]
    setting_utils.modify_main_settings(
        flask_app_client,
        admin_user,
        vals,
        'site.species',
    )
    # test disabled
    agns = auto_name_utils.read_all_autogen_names(flask_app_client, admin_user)
    assert agn_guid in agns
    assert not agns[agn_guid]['enabled']
