# -*- coding: utf-8 -*-
"""
Autogenerated_names resources utils
-------------
"""
import json

from tests import utils as test_utils

PATH = '/api/v1/autogenerated_names/'


def create_autogen_name(
    flask_app_client, user, data, expected_status_code=200, expected_error=''
):

    with flask_app_client.login(user, auth_scopes=('AutogeneratedNames:write',)):
        response = flask_app_client.post(
            '%s' % PATH,
            content_type='application/json',
            data=json.dumps(data),
        )

    if expected_status_code == 200:
        test_utils.validate_dict_response(response, 200, {'guid'})
    elif 400 <= expected_status_code < 500:
        test_utils.validate_dict_response(
            response, expected_status_code, {'status', 'message'}
        )
        assert response.json['message'] == expected_error, response.json['message']
    else:
        test_utils.validate_dict_response(
            response, expected_status_code, {'status', 'message'}
        )
    return response


def read_autogen_name(flask_app_client, user, name_guid, expected_status_code=200):
    return test_utils.get_dict_via_flask(
        flask_app_client,
        user,
        scopes='AutogeneratedNames:read',
        path=f'{PATH}{name_guid}',
        expected_status_code=expected_status_code,
        response_200={'guid'},
    )


def read_all_autogen_names(
    flask_app_client,
    user,
    expected_status_code=200,
):
    return test_utils.get_list_via_flask(
        flask_app_client,
        user,
        scopes='AutogeneratedNames:read',
        path=PATH,
        expected_status_code=expected_status_code,
        expected_fields={'guid'},
    )
